# name: CI

# on:
#   workflow_dispatch:

# jobs:
#   terraform:
#     name: 'Terraform'
#     env:
#       ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#       ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#       ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#       ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#       TF_VERSION: 1.3.6
#     runs-on: ubuntu-latest
#     environment: production
 
#     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
#     defaults:
#       run:
#         shell: bash
 
#     steps:
#     # Checkout the repository to the GitHub Actions runner
#     - name: Checkout
#       uses: actions/checkout@v2
 
#     - name: 'Terraform Format Base'
#       uses: hashicorp/terraform-github-actions@master
#       with:
#         tf_actions_version: ${{ env.TF_VERSION }}
#         tf_actions_subcommand: 'fmt'
#         tf_actions_working_dir: "./3-deploy-terraform-base/terraform"
         
#     - name: 'Terraform Init Base'
#       uses: hashicorp/terraform-github-actions@master
#       with:
#         tf_actions_version: ${{ env.TF_VERSION }}
#         tf_actions_subcommand: 'init'
#         tf_actions_working_dir: "./3-deploy-terraform-base/terraform"
 
#     - name: 'Terraform Plan Base'
#       uses: hashicorp/terraform-github-actions@master
#       with:
#         tf_actions_version: ${{ env.TF_VERSION }}
#         tf_actions_subcommand: 'plan'
#         tf_actions_working_dir: "./3-deploy-terraform-base/terraform"
 
#     - name: 'Terraform Apply Base'
#       if: github.ref == 'refs/heads/main'
#       uses: hashicorp/terraform-github-actions@master
#       with:
#         tf_actions_version: ${{ env.TF_VERSION }}
#         tf_actions_subcommand: 'apply'
#         tf_actions_working_dir: "./3-deploy-terraform-base/terraform"
